version: '3.8'

services:
  web:
    container_name: mel-fpl
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    restart: unless-stopped